---
- apt: update_cache=yes cache_valid_time=3600

- apt: name={{item}} state=present
  with_items:
    - nginx

- template: src=app.nginx.conf.j2 dest=/etc/nginx/sites-enabled/{{name}}

- file: path=/etc/nginx/sites-available/default state=absent

- file: path=/etc/nginx/sites-enabled/default state=absent

- service: name=nginx state=restarted
  sudo: yes